/* Generated By:JJTree: Do not edit this line. ASTDivideEqualsStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTDivideEqualsStatement extends SimpleNode {
  public ASTDivideEqualsStatement(int id) {
    super(id);
  }

  public ASTDivideEqualsStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a54362af29f72c920e8b217e09b7ebb5 (do not edit this line) */
