/* Generated By:JJTree: Do not edit this line. ASTDataStructGetVal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTDataStructGetVal extends SimpleNode {
  public ASTDataStructGetVal(int id) {
    super(id);
  }

  public ASTDataStructGetVal(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61dd6545bb5413fbe090af66da5cb8c1 (do not edit this line) */
