/* Generated By:JJTree: Do not edit this line. ASTPlusEqualsStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTPlusEqualsStatement extends SimpleNode {
  public ASTPlusEqualsStatement(int id) {
    super(id);
  }

  public ASTPlusEqualsStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0e7a10b16746d8856cae36b25afbd822 (do not edit this line) */
