/* Generated By:JJTree: Do not edit this line. ASTRealConst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

import wci.intermediate.icodeimpl.ICodeKeyImpl;

public
class ASTRealConst extends SimpleNode {
  public ASTRealConst(int id) {
    super(id);
  }

  public ASTRealConst(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    void setAttribute(ICodeKeyImpl iCodeKeyImpl, float parseFloat)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
/* JavaCC - OriginalChecksum=a9c71bab30d00ed0fff947cd1b8bbcb7 (do not edit this line) */
