/* Generated By:JJTree: Do not edit this line. ASTvariableDeclDataStruct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTvariableDeclDataStruct extends SimpleNode {
  public ASTvariableDeclDataStruct(int id) {
    super(id);
  }

  public ASTvariableDeclDataStruct(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6407e665046df35506b6efd90ae6720 (do not edit this line) */
