/* Generated By:JJTree: Do not edit this line. ASTWhileIncrementCond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTWhileIncrementCond extends SimpleNode {
  public ASTWhileIncrementCond(int id) {
    super(id);
  }

  public ASTWhileIncrementCond(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=47bcb31d76f0c865b74d10dd5d7bcfa5 (do not edit this line) */
