/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package wci.frontend;

public interface ExprParserTreeConstants
{
  public int JJTHANDLEERROR = 0;
  public int JJTERROR = 1;
  public int JJTPROGRAM = 2;
  public int JJTPROCEDURECALL = 3;
  public int JJTPROCEDURE = 4;
  public int JJTPARAMETERS = 5;
  public int JJTVALUEPASS = 6;
  public int JJTCOMMANDS = 7;
  public int JJTPRINTSTATEMENT = 8;
  public int JJTLITERAL = 9;
  public int JJTVOID = 10;
  public int JJTINTEGERCONST = 11;
  public int JJTBOOLEANCONST = 12;
  public int JJTFLOATCONST = 13;
  public int JJTDOUBLECONST = 14;
  public int JJTSTRINGCONST = 15;
  public int JJTNOTEQUALS = 16;
  public int JJTLESSTHAN = 17;
  public int JJTLESSEQUALS = 18;
  public int JJTGREATERTHAN = 19;
  public int JJTGREATEREQUALS = 20;
  public int JJTEQUALS = 21;
  public int JJTADD = 22;
  public int JJTSUBTRACT = 23;
  public int JJTOR = 24;
  public int JJTMULTIPLY = 25;
  public int JJTDIVIDE = 26;
  public int JJTAND = 27;
  public int JJTNEGATE = 28;
  public int JJTSTATEMENT = 29;
  public int JJTIFPART = 30;
  public int JJTELSEIFPART = 31;
  public int JJTELSEPART = 32;
  public int JJTSWITCHPART = 33;
  public int JJTCOMPARISONOPERATOR = 34;
  public int JJTCASES = 35;
  public int JJTASSIGNMENT = 36;
  public int JJTVARIABLE = 37;
  public int JJTVARIABLEDECL = 38;
  public int JJTDECLARATION = 39;
  public int JJTINCREMENTSTATEMENT = 40;
  public int JJTDECREMENTSTATEMENT = 41;
  public int JJTPLUSEQUALSSTATEMENT = 42;
  public int JJTMINUSEQUALSSTATEMENT = 43;
  public int JJTSTAREQUALSSTATEMENT = 44;
  public int JJTDIVIDEEQUALSSTATEMENT = 45;
  public int JJTFOR = 46;
  public int JJTDECVAR = 47;
  public int JJTTESTCOND = 48;
  public int JJTWHILEINCREMENTCOND = 49;
  public int JJTINCREMENTCOND = 50;
  public int JJTWHILE = 51;
  public int JJTSETADD = 52;
  public int JJTLISTADD = 53;
  public int JJTMAPADD = 54;
  public int JJTPOSITION = 55;
  public int JJTSETDELETE = 56;
  public int JJTLISTDELETE = 57;
  public int JJTMAPDELETE = 58;
  public int JJTLISTGETVAL = 59;
  public int JJTMAPGETVAL = 60;
  public int JJTLISTGETINDEX = 61;
  public int JJTSTRINGGETINDEX = 62;
  public int JJTSTRINGGETSIZE = 63;
  public int JJTSTRINGSUBSTRING = 64;
  public int JJTSTRINGAPPEND = 65;
  public int JJTSETCONTAINS = 66;
  public int JJTMAPCONTAINS = 67;
  public int JJTLISTGETSIZE = 68;
  public int JJTSETGETSIZE = 69;
  public int JJTMAPGETSIZE = 70;
  public int JJTSETGETSTRING = 71;
  public int JJTMAPGETSTRING = 72;
  public int JJTLISTSETVAL = 73;
  public int JJTHASHSETVAL = 74;
  public int JJTVALUE = 75;
  public int JJTKEYTYPE = 76;
  public int JJTVALUETYPE = 77;
  public int JJTSIZE = 78;
  public int JJTHASHMAP = 79;
  public int JJTSET = 80;
  public int JJTLIST = 81;


  public String[] jjtNodeName = {
    "handleError",
    "Error",
    "Program",
    "ProcedureCall",
    "Procedure",
    "Parameters",
    "ValuePass",
    "Commands",
    "PrintStatement",
    "Literal",
    "void",
    "IntegerConst",
    "BooleanConst",
    "FloatConst",
    "DoubleConst",
    "StringConst",
    "NotEquals",
    "LessThan",
    "LessEquals",
    "GreaterThan",
    "GreaterEquals",
    "Equals",
    "add",
    "subtract",
    "or",
    "multiply",
    "divide",
    "and",
    "Negate",
    "Statement",
    "IfPart",
    "ElseIfPart",
    "ElsePart",
    "SwitchPart",
    "ComparisonOperator",
    "Cases",
    "Assignment",
    "variable",
    "variableDecl",
    "Declaration",
    "IncrementStatement",
    "DecrementStatement",
    "PlusEqualsStatement",
    "MinusEqualsStatement",
    "StarEqualsStatement",
    "DivideEqualsStatement",
    "For",
    "DecVar",
    "TestCond",
    "WhileIncrementCond",
    "IncrementCond",
    "While",
    "SetAdd",
    "ListAdd",
    "MapAdd",
    "Position",
    "SetDelete",
    "ListDelete",
    "MapDelete",
    "ListGetVal",
    "MapGetVal",
    "ListGetIndex",
    "StringGetIndex",
    "StringGetSize",
    "StringSubstring",
    "StringAppend",
    "SetContains",
    "MapContains",
    "ListGetSize",
    "SetGetSize",
    "MapGetSize",
    "SetGetString",
    "MapGetString",
    "ListSetVal",
    "HashSetVal",
    "value",
    "KeyType",
    "ValueType",
    "Size",
    "Hashmap",
    "Set",
    "List",
  };
}
/* JavaCC - OriginalChecksum=cee0ee419dfd5b1a2d1fa49d13dffdf9 (do not edit this line) */
