/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 6.0_1 */
package wci.frontend;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASThandleError node, Object data);
  public Object visit(ASTError node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTCommands node, Object data);
  public Object visit(ASTPrimitiveType node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTSimpleExpr node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTIfPart node, Object data);
  public Object visit(ASTElseIfPart node, Object data);
  public Object visit(ASTElsePart node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIntegerConst node, Object data);
  public Object visit(ASTRealConst node, Object data);
  public Object visit(ASTStringConst node, Object data);
  public Object visit(ASTSwitchPart node, Object data);
  public Object visit(ASTComparisonOperator node, Object data);
  public Object visit(ASTCases node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTvariable node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTIncrementStatement node, Object data);
  public Object visit(ASTDecrementStatement node, Object data);
  public Object visit(ASTPlusEqualsStatement node, Object data);
  public Object visit(ASTMinusEqualsStatement node, Object data);
  public Object visit(ASTStarEqualsStatement node, Object data);
  public Object visit(ASTDivideEqualsStatement node, Object data);
  public Object visit(ASTFor node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTDataTypes node, Object data);
  public Object visit(ASTHashmap node, Object data);
  public Object visit(ASTSet node, Object data);
  public Object visit(ASTList node, Object data);
}
/* JavaCC - OriginalChecksum=09b4c45a64db43810b56b95f55d33afb (do not edit this line) */
