/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface ExprParserTreeConstants
{
  public int JJTHANDLEERROR = 0;
  public int JJTERROR = 1;
  public int JJTPROGRAM = 2;
  public int JJTPROCEDURE = 3;
  public int JJTCOMMANDS = 4;
  public int JJTVOID = 5;
  public int JJTINTEGERCONST = 6;
  public int JJTREALCONST = 7;
  public int JJTSTRINGCONST = 8;
  public int JJTADD = 9;
  public int JJTSUBTRACT = 10;
  public int JJTOR = 11;
  public int JJTMULTIPLY = 12;
  public int JJTDIVIDE = 13;
  public int JJTAND = 14;
  public int JJTSTATEMENT = 15;
  public int JJTIFPART = 16;
  public int JJTELSEIFPART = 17;
  public int JJTELSEPART = 18;
  public int JJTSWITCHPART = 19;
  public int JJTCOMPARISONOPERATOR = 20;
  public int JJTCASES = 21;
  public int JJTASSIGNMENT = 22;
  public int JJTVARIABLE = 23;
  public int JJTVARIABLEDECL = 24;
  public int JJTDECLARATION = 25;
  public int JJTINCREMENTSTATEMENT = 26;
  public int JJTDECREMENTSTATEMENT = 27;
  public int JJTPLUSEQUALSSTATEMENT = 28;
  public int JJTMINUSEQUALSSTATEMENT = 29;
  public int JJTSTAREQUALSSTATEMENT = 30;
  public int JJTDIVIDEEQUALSSTATEMENT = 31;
  public int JJTFOR = 32;
  public int JJTDECVAR = 33;
  public int JJTTESTCOND = 34;
  public int JJTWHILEINCREMENTCOND = 35;
  public int JJTINCREMENTCOND = 36;
  public int JJTWHILE = 37;
  public int JJTDATATYPES = 38;
  public int JJTHASHMAP = 39;
  public int JJTSET = 40;
  public int JJTLIST = 41;


  public String[] jjtNodeName = {
    "handleError",
    "Error",
    "Program",
    "Procedure",
    "Commands",
    "void",
    "IntegerConst",
    "RealConst",
    "StringConst",
    "add",
    "subtract",
    "or",
    "multiply",
    "divide",
    "and",
    "Statement",
    "IfPart",
    "ElseIfPart",
    "ElsePart",
    "SwitchPart",
    "ComparisonOperator",
    "Cases",
    "Assignment",
    "variable",
    "variableDecl",
    "Declaration",
    "IncrementStatement",
    "DecrementStatement",
    "PlusEqualsStatement",
    "MinusEqualsStatement",
    "StarEqualsStatement",
    "DivideEqualsStatement",
    "For",
    "DecVar",
    "TestCond",
    "WhileIncrementCond",
    "IncrementCond",
    "While",
    "DataTypes",
    "Hashmap",
    "Set",
    "List",
  };
}
/* JavaCC - OriginalChecksum=4c52ac915ff423013e0bc8582faf06f0 (do not edit this line) */
