/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 5.0 */
package wci.frontend;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASThandleError node, Object data);
  public Object visit(ASTError node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTProcedureCall node, Object data);
  public Object visit(ASTProcedure node, Object data);
  public Object visit(ASTCommands node, Object data);
  public Object visit(ASTPrintStatement node, Object data);
  public Object visit(ASTIntegerConst node, Object data);
  public Object visit(ASTBooleanConst node, Object data);
  public Object visit(ASTRealConst node, Object data);
  public Object visit(ASTStringConst node, Object data);
  public Object visit(ASTNotEquals node, Object data);
  public Object visit(ASTLessThan node, Object data);
  public Object visit(ASTLessEquals node, Object data);
  public Object visit(ASTGreaterThan node, Object data);
  public Object visit(ASTGreaterEquals node, Object data);
  public Object visit(ASTEquals node, Object data);
  public Object visit(ASTadd node, Object data);
  public Object visit(ASTsubtract node, Object data);
  public Object visit(ASTor node, Object data);
  public Object visit(ASTmultiply node, Object data);
  public Object visit(ASTdivide node, Object data);
  public Object visit(ASTand node, Object data);
  public Object visit(ASTNegate node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTIfPart node, Object data);
  public Object visit(ASTElseIfPart node, Object data);
  public Object visit(ASTElsePart node, Object data);
  public Object visit(ASTSwitchPart node, Object data);
  public Object visit(ASTComparisonOperator node, Object data);
  public Object visit(ASTCases node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTvariable node, Object data);
  public Object visit(ASTvariableDecl node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTIncrementStatement node, Object data);
  public Object visit(ASTDecrementStatement node, Object data);
  public Object visit(ASTPlusEqualsStatement node, Object data);
  public Object visit(ASTMinusEqualsStatement node, Object data);
  public Object visit(ASTStarEqualsStatement node, Object data);
  public Object visit(ASTDivideEqualsStatement node, Object data);
  public Object visit(ASTFor node, Object data);
  public Object visit(ASTDecVar node, Object data);
  public Object visit(ASTTestCond node, Object data);
  public Object visit(ASTWhileIncrementCond node, Object data);
  public Object visit(ASTIncrementCond node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTDataStructAdd node, Object data);
  public Object visit(ASTDataStructDelete node, Object data);
  public Object visit(ASTDataStructGetVal node, Object data);
  public Object visit(ASTDataStructGetIndex node, Object data);
  public Object visit(ASTDataStructSetVal node, Object data);
  public Object visit(ASTDataTypes node, Object data);
  public Object visit(ASTHashmap node, Object data);
  public Object visit(ASTSet node, Object data);
  public Object visit(ASTList node, Object data);
}
/* JavaCC - OriginalChecksum=91ed33441f0625a4103c304c7f2b6d0c (do not edit this line) */
