/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface ExprParserTreeConstants
{
  public int JJTHANDLEERROR = 0;
  public int JJTERROR = 1;
  public int JJTPROGRAM = 2;
  public int JJTPROCEDURECALL = 3;
  public int JJTPROCEDURE = 4;
  public int JJTCOMMANDS = 5;
  public int JJTPRINTSTATEMENT = 6;
  public int JJTLITERAL = 7;
  public int JJTVOID = 8;
  public int JJTINTEGERCONST = 9;
  public int JJTBOOLEANCONST = 10;
  public int JJTREALCONST = 11;
  public int JJTSTRINGCONST = 12;
  public int JJTNOTEQUALS = 13;
  public int JJTLESSTHAN = 14;
  public int JJTLESSEQUALS = 15;
  public int JJTGREATERTHAN = 16;
  public int JJTGREATEREQUALS = 17;
  public int JJTEQUALS = 18;
  public int JJTADD = 19;
  public int JJTSUBTRACT = 20;
  public int JJTOR = 21;
  public int JJTMULTIPLY = 22;
  public int JJTDIVIDE = 23;
  public int JJTAND = 24;
  public int JJTNEGATE = 25;
  public int JJTSTATEMENT = 26;
  public int JJTIFPART = 27;
  public int JJTELSEIFPART = 28;
  public int JJTELSEPART = 29;
  public int JJTSWITCHPART = 30;
  public int JJTCOMPARISONOPERATOR = 31;
  public int JJTCASES = 32;
  public int JJTASSIGNMENT = 33;
  public int JJTVARIABLE = 34;
  public int JJTVARIABLEDECL = 35;
  public int JJTDECLARATION = 36;
  public int JJTFUNCTION = 37;
  public int JJTINCREMENTSTATEMENT = 38;
  public int JJTDECREMENTSTATEMENT = 39;
  public int JJTPLUSEQUALSSTATEMENT = 40;
  public int JJTMINUSEQUALSSTATEMENT = 41;
  public int JJTSTAREQUALSSTATEMENT = 42;
  public int JJTDIVIDEEQUALSSTATEMENT = 43;
  public int JJTFOR = 44;
  public int JJTDECVAR = 45;
  public int JJTTESTCOND = 46;
  public int JJTWHILEINCREMENTCOND = 47;
  public int JJTINCREMENTCOND = 48;
  public int JJTWHILE = 49;
  public int JJTSETADD = 50;
  public int JJTLISTADD = 51;
  public int JJTMAPADD = 52;
  public int JJTPOSITION = 53;
  public int JJTSETDELETE = 54;
  public int JJTLISTDELETE = 55;
  public int JJTMAPDELETE = 56;
  public int JJTSETGETVAL = 57;
  public int JJTLISTGETVAL = 58;
  public int JJTMAPGETVAL = 59;
  public int JJTLISTGETINDEX = 60;
  public int JJTSETSETVAL = 61;
  public int JJTLISTSETVAL = 62;
  public int JJTHASHSETVAL = 63;
  public int JJTKEYTYPE = 64;
  public int JJTVALUETYPE = 65;
  public int JJTSIZE = 66;
  public int JJTHASHMAP = 67;
  public int JJTSET = 68;
  public int JJTLIST = 69;


  public String[] jjtNodeName = {
    "handleError",
    "Error",
    "Program",
    "ProcedureCall",
    "Procedure",
    "Commands",
    "PrintStatement",
    "Literal",
    "void",
    "IntegerConst",
    "BooleanConst",
    "RealConst",
    "StringConst",
    "NotEquals",
    "LessThan",
    "LessEquals",
    "GreaterThan",
    "GreaterEquals",
    "Equals",
    "add",
    "subtract",
    "or",
    "multiply",
    "divide",
    "and",
    "Negate",
    "Statement",
    "IfPart",
    "ElseIfPart",
    "ElsePart",
    "SwitchPart",
    "ComparisonOperator",
    "Cases",
    "Assignment",
    "variable",
    "variableDecl",
    "Declaration",
    "Function",
    "IncrementStatement",
    "DecrementStatement",
    "PlusEqualsStatement",
    "MinusEqualsStatement",
    "StarEqualsStatement",
    "DivideEqualsStatement",
    "For",
    "DecVar",
    "TestCond",
    "WhileIncrementCond",
    "IncrementCond",
    "While",
    "SetAdd",
    "ListAdd",
    "MapAdd",
    "Position",
    "SetDelete",
    "ListDelete",
    "MapDelete",
    "SetGetVal",
    "ListGetVal",
    "MapGetVal",
    "ListGetIndex",
    "SetSetVal",
    "ListSetVal",
    "HashSetVal",
    "KeyType",
    "ValueType",
    "Size",
    "Hashmap",
    "Set",
    "List",
  };
}
/* JavaCC - OriginalChecksum=13beed2f5c32454f6a6f1d73a9e832a8 (do not edit this line) */
