/* Generated By:JJTree: Do not edit this line. ASTComparisonOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComparisonOperator extends SimpleNode {
  public ASTComparisonOperator(int id) {
    super(id);
  }

  public ASTComparisonOperator(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f2e941661c095517bbb64ebd83d4de4f (do not edit this line) */
