/* Generated By:JJTree: Do not edit this line. ASTDataTypes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDataTypes extends SimpleNode {
  public ASTDataTypes(int id) {
    super(id);
  }

  public ASTDataTypes(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=354a55cf381ec5d286b7841bfd219284 (do not edit this line) */
