/* Generated By:JJTree: Do not edit this line. ASTDecrementStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecrementStatement extends SimpleNode {
  public ASTDecrementStatement(int id) {
    super(id);
  }

  public ASTDecrementStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd3ff5e2f4b1d231bef522d5061affbb (do not edit this line) */
