/* Generated By:JJTree: Do not edit this line. ASTElseIfPart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseIfPart extends SimpleNode {
  public ASTElseIfPart(int id) {
    super(id);
  }

  public ASTElseIfPart(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=17189db1853b508b15cf878605cea0fb (do not edit this line) */
