/* Generated By:JJTree: Do not edit this line. ASTIncrementStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIncrementStatement extends SimpleNode {
  public ASTIncrementStatement(int id) {
    super(id);
  }

  public ASTIncrementStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57301ece5222bcf8a6defdc089d0031f (do not edit this line) */
