/* Generated By:JJTree: Do not edit this line. ASTMinusEqualsStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinusEqualsStatement extends SimpleNode {
  public ASTMinusEqualsStatement(int id) {
    super(id);
  }

  public ASTMinusEqualsStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d37ecffc2acee8c704c62a387e1df638 (do not edit this line) */
