/* Generated By:JJTree: Do not edit this line. ASTPlusEqualsStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPlusEqualsStatement extends SimpleNode {
  public ASTPlusEqualsStatement(int id) {
    super(id);
  }

  public ASTPlusEqualsStatement(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c5bdee56b1da9cb468640b90858d156c (do not edit this line) */
