/* Generated By:JJTree: Do not edit this line. ASTSimpleExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimpleExpr extends SimpleNode {
  public ASTSimpleExpr(int id) {
    super(id);
  }

  public ASTSimpleExpr(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea348d4f9e7569ce8eef7767fa52a509 (do not edit this line) */
