/* Generated By:JJTree: Do not edit this line. ASTSwitchPart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSwitchPart extends SimpleNode {
  public ASTSwitchPart(int id) {
    super(id);
  }

  public ASTSwitchPart(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c5aced3eaf69f86ea2318256194bdfa7 (do not edit this line) */
