/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
public interface ExprParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTPRIMITIVETYPE = 1;
  public int JJTEXPR = 2;
  public int JJTSIMPLEEXPR = 3;
  public int JJTTERM = 4;
  public int JJTFACTOR = 5;
  public int JJTSTATEMENT = 6;
  public int JJTIFPART = 7;
  public int JJTELSEIFPART = 8;
  public int JJTELSEPART = 9;
  public int JJTLITERAL = 10;
  public int JJTSWITCHPART = 11;
  public int JJTCOMPARISONOPERATOR = 12;
  public int JJTCASES = 13;
  public int JJTASSIGNMENT = 14;
  public int JJTDECLARATION = 15;
  public int JJTINCREMENTSTATEMENT = 16;
  public int JJTDECREMENTSTATEMENT = 17;
  public int JJTPLUSEQUALSSTATEMENT = 18;
  public int JJTMINUSEQUALSSTATEMENT = 19;
  public int JJTSTAREQUALSSTATEMENT = 20;
  public int JJTDIVIDEEQUALSSTATEMENT = 21;
  public int JJTDATATYPES = 22;
  public int JJTHASHMAP = 23;
  public int JJTSET = 24;
  public int JJTLIST = 25;


  public String[] jjtNodeName = {
    "Program",
    "PrimitiveType",
    "Expr",
    "SimpleExpr",
    "Term",
    "Factor",
    "Statement",
    "IfPart",
    "ElseIfPart",
    "ElsePart",
    "Literal",
    "SwitchPart",
    "ComparisonOperator",
    "Cases",
    "Assignment",
    "Declaration",
    "IncrementStatement",
    "DecrementStatement",
    "PlusEqualsStatement",
    "MinusEqualsStatement",
    "StarEqualsStatement",
    "DivideEqualsStatement",
    "DataTypes",
    "Hashmap",
    "Set",
    "List",
  };
}
/* JavaCC - OriginalChecksum=3cb294a1245311ec06ae0fa1eb163201 (do not edit this line) */
